INSERT INTO PERSON (NAME, AGE) VALUES ('John' , 20);
INSERT INTO PERSON (NAME, AGE) VALUES ('John' , 21);
INSERT INTO PERSON (NAME, AGE) VALUES ('Bill' , 30);
INSERT INTO PERSON (NAME, AGE) VALUES ('Nancy', 40);
INSERT INTO PERSON (NAME, AGE) VALUES ('Susan', 50);
